### ISSUE TITLE
[Bug] Social Interaction screen not working

### ISSUE THREAD

**Issue by SB2DD** [Mrredstone5230/BetterMsgPlus#2]
If you block a user using the Social Interaction Screen, private messages (/msg and /r) are not blocked

**Comment by SB2DD** [comment]
That may actually a good thing (to avoid the new mojang report bullcrap)

**Comment by emielderckx** [comment]
I would still love if this gets fixed if you have time for this. Would be a great help to me.

**Comment by SB2DD** [comment]
Hmm. I just looked at the way Minecraft handles their /msg command (with the new chat signing and stuff) and unfortunately I can't really do much on Spigot. Adding this feature would require doing heavy NMS and I'm not very confortable doing it that way, sorry. If by any chance though you wanted to take this challenge, feel free to try and I would happily merge your changes in the code. I'm deeply sorry.
