### ISSUE TITLE
Make messages configurable 

### ISSUE THREAD

**Issue by emielderckx** [Mrredstone5230/BetterMsgPlus#4]
I would appreciate it if messages were configurable, so people could easily change the plugin's messages without forking the plugin.

**Comment by SB2DD** [comment]
Will do, thanks!

**Comment by SB2DD** [comment]
commit fed264ea69347e2d1561032b509032781561ebbf (forgot to mention the issue # in it)

**Comment by SB2DD** [comment]
Feature added on v1.4 which is now in the releases tab and on spigotmc.org. Thank you for your suggestion!!!

**Comment by emielderckx** [comment]
Thanks a lot! Would still be great to be able to use adventure/minimessage in the messages for more design options, but this is already really helpful, thanks!
